'use client'

import 'reflect-metadata';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { container } from "tsyringe";
import { AppService } from "@/view-models/misc/app.service";
import { SyntheticEvent, useReducer, useState } from "react";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fas } from "@fortawesome/free-solid-svg-icons";
import { far } from "@fortawesome/free-regular-svg-icons";
import { fab } from "@fortawesome/free-brands-svg-icons";
import Login from "./login";
import { GlobalVars } from "@/common/common";
import * as React from "react";
import { AppBar, Tab, Tabs } from "@mui/material";
import Link from "next/link";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { usePathname } from "next/navigation";

// import "font-awesome/css/font-awesome.min.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const appService = container.resolve(AppService);
  const pathname = usePathname();
  console.log(appService);
  const items2 = [
    {label: 'Words in Unit', icon: 'bus', url: '/words-unit2'},
    {label: 'Phrases in Unit', icon: 'train', url: '/phrases-unit2'},
    {label: 'Words in Textbook', icon: 'car', url: '/words-textbook2'},
    {label: 'Phrases in Textbook', icon: 'taxi', url: '/phrases-textbook2'},
    {label: 'Words in Language', icon: 'plane', url: '/words-lang2'},
    {label: 'Phrases in Language', icon: 'rocket', url: '/phrases-lang2'},
    {label: 'Patterns in Language', icon: 'motorcycle', url: '/patterns2'},
    {label: 'Settings', icon: 'cog', url: '/settings'},
  ];
  const indexTab2 = items2.findIndex(o => pathname == o.url);
  library.add(fas as any, far as any, fab as any);

  const loggedIn = localStorage.getItem('userid');
  if (!loggedIn)
    return (
      <html lang="en">
      <body className={inter.className}>
        <Login/>
      </body>
      </html>
    );

  GlobalVars.userid = loggedIn!;
  appService.getData();

  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="App">
        <h2>Lolly React Next</h2>
        <AppBar position="static" color="default">
          <Tabs value={indexTab2} indicatorColor="primary" textColor="primary">
            {items2.map((row: any) =>
              // https://stackoverflow.com/questions/65471275/material-ui-tabs-with-nextjs
              <Link key={row.url} href={row.url} passHref>
                <Tab key={row.label} label={<span><FontAwesomeIcon icon={row.icon} size="lg"/> {row.label}</span>}/>
              </Link>
            )}
          </Tabs>
        </AppBar>
        {children}
      </div>
    </body>
    </html>
  );
}
